version: '3.8'

services:
  app:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mediasoup
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network: