version: '3.8'

services:
  app:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mediasoup
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - MYSQL_DATABASE=user_management
      - STREAM_BASE_URL=http://localhost:3000
      - STREAM_VOLUME_PATH=/video-storage
      - JWT_SECRET=v6k5rosZ5cprLTChxj5wEbGO8h4XHGPe
    volumes:
      - video-storage:/video-storage
    depends_on:
      - mongo
      - mysql
    networks:
      - app-network

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: user_management
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    networks:
      - app-network

volumes:
  mongo-data:
  mysql-data:
  video-storage:
    driver: local

networks:
  app-network: